apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-rest-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/devisri1/CI-CD-Pipeline.git
    targetRevision: HEAD
    path: deployment
  destination:
    server: https://kubernetes.docker.internal:6443 # K8s on Docker Desktop
    namespace: go-app
  syncPolicy:
    automated:
      selfHeal: true